version: "3.0"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5294:80"
      
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=baghchal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  baghchal:
    driver: bridge